[tools]
awscli = "2.13.5"
elixir = "1.15.4-otp-26"
erlang = "26.0.2"
go = "1.20.6"
helm = "3.12.2"
kubectl = "1.27.4"
poetry = "1.5.1"
python = "3.11.4"
terraform = "1.5.4"

[settings]
experimental = true
