[tools]
awscli = "2.15.6"
elixir = "1.16.0-otp-26"
erlang = "26.2.1"
go = "1.21.5"
helm = "3.13.3"
kubectl = "1.29.0"
lefthook = "1.5.5"
node = "21.5.0"
poetry = "1.7.1"
python = "3.12.1"
terraform = "1.6.6"
tilt = "0.33.10"
usql = "0.17.2"
yarn = "1.22.19"

[settings]
experimental = true
