[tools]
awscli = "2.13.30"
elixir = "1.15.7-otp-26"
erlang = "26.1.2"
go = "1.21.3"
helm = "3.13.1"
kubectl = "1.27.7"
node = "21.1.0"
poetry = "1.6.1"
python = "3.12.0"
terraform = "1.6.2"

[settings]
experimental = true
