[tools]
age = "1.2.0"
awscli = "2.18.14"
bat = "0.24.0"
bitwarden = "2024.9.0"
circleci-cli = "0.1.30995"
ctlptl = "0.8.34"
dagger = "0.13.5"
eksctl = "0.193.0"
elixir = "1.17.3"
erlang = "27.1.2"
eza = "0.20.4"
fzf = "0.55.0"
github-cli = "2.59.0"
go = "1.23.2"
helm = "3.16.2"
k3d = "5.7.4"
k3sup = "0.13.7"
k9s = "0.32.5"
kind = "0.24.0"
kubectl = "1.31.1"
kubie = "0.24.0"
lefthook = "1.8.0"
lua = "5.1.5"
luajit = "2.0.5--2.4.4"
node = "22.10.0"
poetry = "1.8.4"
python = "3.13.0"
r = "4.4.1"
ripgrep = "14.1.1"
rust = "1.82.0"
starship = "1.21.1"
task = "3.39.2"
terraform = "1.9.8"
tilt = "0.33.20"
usage = "0.11.0"
usql = "0.19.4"
yarn = "1.22.22"
zoxide = "0.9.6"

[settings]
experimental = true
python_compile = true
