[tools]
age = "1.2.0"
awscli = "2.17.62"
bat = "0.24.0"
bitwarden = "2024.7.2"
circleci-cli = "0.1.30549"
ctlptl = "0.8.31"
dagger = "0.12.5"
eksctl = "0.188.0"
elixir = "1.17.3"
erlang = "27.1.1"
eza = "0.19.0"
fzf = "0.53.0"
go = "1.23.2"
helm = "3.16.1"
k3d = "5.7.3"
k3sup = "0.13.7"
k9s = "0.32.5"
kind = "0.24.0"
kubectl = "1.31.1"
kubie = "0.23.1"
lefthook = "1.7.13"
lua = "5.1.5"
luajit = "2.0.5--2.4.4"
node = "22.9.0"
poetry = "1.8.3"
python = "3.12.7"
r = "4.4.1"
ripgrep = "14.1.0"
rust = "1.81.0"
starship = "1.20.1"
task = "3.38.0"
terraform = "1.9.6"
tilt = "0.33.19"
tmux = "3.4"
usage = "0.3.0"
usql = "0.19.3"
yarn = "1.22.22"
zoxide = "0.9.4"

[settings]
experimental = true
python_compile = true
