[tools]
awscli = "2.15.30"
bat = "0.24.0"
bitwarden = "2024.2.1"
dagger = "0.10.2"
elixir = "1.16.2-otp-26"
erlang = "26.2.3"
eza = "0.18.7"
fzf = "0.48.1"
go = "1.22.1"
helm = "3.14.3"
k3d = "5.6.0"
k3sup = "0.13.5"
k9s = "0.32.3"
kubectl = "1.29.3"
kubie = "0.23.0"
lefthook = "1.6.7"
lua = "5.4.6"
luajit = "2.0.5--2.4.4"
node = "21.7.1"
poetry = "1.8.2"
python = "3.12.2"
ripgrep = "14.1.0"
rust = "1.76.0"
starship = "1.17.1"
terraform = "1.7.5"
tilt = "0.33.11"
tmux = "3.4"
usql = "0.17.5"
yarn = "1.22.19"
zoxide = "0.9.4"

[settings]
experimental = true
python_compile = true
